# Generated by Django 5.0.6 on 2024-08-05 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_default_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Employee = apps.get_model('auth_app', 'Employee')
    default_user = User.objects.first()
    if default_user:
        Employee.objects.filter(user=None).update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(set_default_user, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
